name: Check and build site

on:
  pull_request:
    branches:
      - main

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24']
    name: Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Check format
        run: pnpm run format
      - name: Lint
        run: pnpm run lint
      - name: Astro check
        run: pnpm astro check
      - name: Build site
        run: pnpm run build
